language: go
os: linux

cache:
  directories:
    - "$HOME/.cache/go-build"
    - "$HOME/gopath/pkg/mod"

env:
  global:
    - CODECLIMATE=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - GO111MODULE=on

go:
  - master
  - 1.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x

jobs:
  allow_failures:
    - go: master

before_script:
  - make env deps-fetch
  - |
    if [[ $TRAVIS_GO_VERSION == 1.16* ]]; then
      curl -sL $CODECLIMATE > /home/travis/gopath/bin/cc-test-reporter
      chmod +x /home/travis/gopath/bin/cc-test-reporter
      cc-test-reporter before-build
    fi

script:
  - |
    if [[ $TRAVIS_GO_VERSION == 1.16* ]]; then
      make test-with-coverage
    else
      make test
    fi

after_script:
  - |
    if [[ $TRAVIS_GO_VERSION == 1.16* ]]; then
      sed -i "s|$(go list -m)/||g" c.out # https://github.com/codeclimate/test-reporter/issues/378
      cc-test-reporter after-build -t gocov -p $(go list -m) --exit-code $TRAVIS_TEST_RESULT
    fi

notifications:
  slack:
    secure: zrU1KX6sTYYHIqMUSnX+Nwk0g6u8F2u5DNurq/ivoQchbgdkQxVtuGf5WVqCn4t6/Tb0tUeU2mDNfQ9DwWEmuSyg+gfzVf6XkygX4iW+OR5OKv+WNUWtIfCtL3OaOTMpHK++higUgC/orxfTKLsO1UxSG5pmGleBTWid2B6JHoPn4qO6SP3HdG8dgp9dy9BScSpsr4LrKV8vZ8/HhvMbOcU9KhjH3r7Fdhbf6PVF5zOD+3+1qVF61p6g7XCbPQbqGPYLbO4147CmyNqiIptrUSXxBSzEUAdP4bYLeM6VQ38HAlqmyPQfNh4VvBRE2JT1MEK+fNnHRavKjbzQdNeub7JV7l1HTlIR8ZpUOW+gCn8gbj5hEeZ+AHtxAIl9FESL+skuy4uaNcKE8PF9OEqx7VrRy1uOF+EZ/5QC+MOjJNIm/+pb9W/LngR8aCDM0Qw/BUABgRaohmGRKBWbQunPHvvlgQ7TRr0c4mGOW0HjO0xCONZYNf97BGh4PJrzSOEYKBgJtKDnw8U5SdNU9FFVkPxnuNpmgGMc63tJ/Kg2WPGz5ZjyzegvQ420Vattay/rlbU+M0TSGz9+WJ0jul7LUtHk8bzqFuDSm6LMuj397PHjJT183mgkNdxOQT69gjuiM5uk/VSKhJX6gB6ayRZUNFdV0Nxh+KDdljNwEM77OlY=
